from setuptools import setup

setup(
    name='BlackJack',
    version='1.22',
    packages=['env.lib.python3.7.distutils', 'env.lib.python3.7.encodings', 'env.lib.python3.7.importlib',
              'env.lib.python3.7.collections', 'env.lib.python3.7.site-packages.jws',
              'env.lib.python3.7.site-packages.pip', 'env.lib.python3.7.site-packages.pip._vendor',
              'env.lib.python3.7.site-packages.pip._vendor.idna', 'env.lib.python3.7.site-packages.pip._vendor.pep517',
              'env.lib.python3.7.site-packages.pip._vendor.pytoml',
              'env.lib.python3.7.site-packages.pip._vendor.certifi',
              'env.lib.python3.7.site-packages.pip._vendor.chardet',
              'env.lib.python3.7.site-packages.pip._vendor.chardet.cli',
              'env.lib.python3.7.site-packages.pip._vendor.distlib',
              'env.lib.python3.7.site-packages.pip._vendor.distlib._backport',
              'env.lib.python3.7.site-packages.pip._vendor.msgpack',
              'env.lib.python3.7.site-packages.pip._vendor.urllib3',
              'env.lib.python3.7.site-packages.pip._vendor.urllib3.util',
              'env.lib.python3.7.site-packages.pip._vendor.urllib3.contrib',
              'env.lib.python3.7.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'env.lib.python3.7.site-packages.pip._vendor.urllib3.packages',
              'env.lib.python3.7.site-packages.pip._vendor.urllib3.packages.backports',
              'env.lib.python3.7.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'env.lib.python3.7.site-packages.pip._vendor.colorama',
              'env.lib.python3.7.site-packages.pip._vendor.html5lib',
              'env.lib.python3.7.site-packages.pip._vendor.html5lib._trie',
              'env.lib.python3.7.site-packages.pip._vendor.html5lib.filters',
              'env.lib.python3.7.site-packages.pip._vendor.html5lib.treewalkers',
              'env.lib.python3.7.site-packages.pip._vendor.html5lib.treeadapters',
              'env.lib.python3.7.site-packages.pip._vendor.html5lib.treebuilders',
              'env.lib.python3.7.site-packages.pip._vendor.lockfile',
              'env.lib.python3.7.site-packages.pip._vendor.progress',
              'env.lib.python3.7.site-packages.pip._vendor.requests',
              'env.lib.python3.7.site-packages.pip._vendor.packaging',
              'env.lib.python3.7.site-packages.pip._vendor.cachecontrol',
              'env.lib.python3.7.site-packages.pip._vendor.cachecontrol.caches',
              'env.lib.python3.7.site-packages.pip._vendor.webencodings',
              'env.lib.python3.7.site-packages.pip._vendor.pkg_resources',
              'env.lib.python3.7.site-packages.pip._internal', 'env.lib.python3.7.site-packages.pip._internal.cli',
              'env.lib.python3.7.site-packages.pip._internal.req', 'env.lib.python3.7.site-packages.pip._internal.vcs',
              'env.lib.python3.7.site-packages.pip._internal.utils',
              'env.lib.python3.7.site-packages.pip._internal.models',
              'env.lib.python3.7.site-packages.pip._internal.commands',
              'env.lib.python3.7.site-packages.pip._internal.operations', 'env.lib.python3.7.site-packages.rsa',
              'env.lib.python3.7.site-packages.click', 'env.lib.python3.7.site-packages.flask',
              'env.lib.python3.7.site-packages.flask.json', 'env.lib.python3.7.site-packages.tests',
              'env.lib.python3.7.site-packages.tests.common', 'env.lib.python3.7.site-packages.tests.asyncio',
              'env.lib.python3.7.site-packages.wheel', 'env.lib.python3.7.site-packages.wheel.cli',
              'env.lib.python3.7.site-packages.Crypto', 'env.lib.python3.7.site-packages.Crypto.IO',
              'env.lib.python3.7.site-packages.Crypto.Hash', 'env.lib.python3.7.site-packages.Crypto.Math',
              'env.lib.python3.7.site-packages.Crypto.Util', 'env.lib.python3.7.site-packages.Crypto.Cipher',
              'env.lib.python3.7.site-packages.Crypto.Random', 'env.lib.python3.7.site-packages.Crypto.Protocol',
              'env.lib.python3.7.site-packages.Crypto.SelfTest', 'env.lib.python3.7.site-packages.Crypto.SelfTest.IO',
              'env.lib.python3.7.site-packages.Crypto.SelfTest.Hash',
              'env.lib.python3.7.site-packages.Crypto.SelfTest.Math',
              'env.lib.python3.7.site-packages.Crypto.SelfTest.Util',
              'env.lib.python3.7.site-packages.Crypto.SelfTest.Cipher',
              'env.lib.python3.7.site-packages.Crypto.SelfTest.Random',
              'env.lib.python3.7.site-packages.Crypto.SelfTest.Protocol',
              'env.lib.python3.7.site-packages.Crypto.SelfTest.PublicKey',
              'env.lib.python3.7.site-packages.Crypto.SelfTest.Signature',
              'env.lib.python3.7.site-packages.Crypto.PublicKey', 'env.lib.python3.7.site-packages.Crypto.Signature',
              'env.lib.python3.7.site-packages.gcloud', 'env.lib.python3.7.site-packages.gcloud.dns',
              'env.lib.python3.7.site-packages.gcloud.pubsub', 'env.lib.python3.7.site-packages.gcloud.logging',
              'env.lib.python3.7.site-packages.gcloud.storage', 'env.lib.python3.7.site-packages.gcloud.bigquery',
              'env.lib.python3.7.site-packages.gcloud.bigtable',
              'env.lib.python3.7.site-packages.gcloud.bigtable.happybase',
              'env.lib.python3.7.site-packages.gcloud.bigtable._generated',
              'env.lib.python3.7.site-packages.gcloud.bigtable._generated_v2',
              'env.lib.python3.7.site-packages.gcloud.datastore',
              'env.lib.python3.7.site-packages.gcloud.datastore._generated',
              'env.lib.python3.7.site-packages.gcloud.streaming', 'env.lib.python3.7.site-packages.gcloud.translate',
              'env.lib.python3.7.site-packages.gcloud.monitoring',
              'env.lib.python3.7.site-packages.gcloud.resource_manager', 'env.lib.python3.7.site-packages.google.api',
              'env.lib.python3.7.site-packages.google.rpc', 'env.lib.python3.7.site-packages.google.type',
              'env.lib.python3.7.site-packages.google.logging.type', 'env.lib.python3.7.site-packages.google.protobuf',
              'env.lib.python3.7.site-packages.google.protobuf.util',
              'env.lib.python3.7.site-packages.google.protobuf.pyext',
              'env.lib.python3.7.site-packages.google.protobuf.compiler',
              'env.lib.python3.7.site-packages.google.protobuf.internal',
              'env.lib.python3.7.site-packages.google.protobuf.internal.import_test_package',
              'env.lib.python3.7.site-packages.google.longrunning', 'env.lib.python3.7.site-packages.jinja2',
              'env.lib.python3.7.site-packages.pyasn1', 'env.lib.python3.7.site-packages.pyasn1.type',
              'env.lib.python3.7.site-packages.pyasn1.codec', 'env.lib.python3.7.site-packages.pyasn1.codec.ber',
              'env.lib.python3.7.site-packages.pyasn1.codec.cer', 'env.lib.python3.7.site-packages.pyasn1.codec.der',
              'env.lib.python3.7.site-packages.pyasn1.codec.native', 'env.lib.python3.7.site-packages.pyasn1.compat',
              'env.lib.python3.7.site-packages.engineio', 'env.lib.python3.7.site-packages.engineio.async_drivers',
              'env.lib.python3.7.site-packages.httplib2', 'env.lib.python3.7.site-packages.pyrebase',
              'env.lib.python3.7.site-packages.requests', 'env.lib.python3.7.site-packages.requests.packages',
              'env.lib.python3.7.site-packages.requests.packages.chardet',
              'env.lib.python3.7.site-packages.requests.packages.urllib3',
              'env.lib.python3.7.site-packages.requests.packages.urllib3.util',
              'env.lib.python3.7.site-packages.requests.packages.urllib3.contrib',
              'env.lib.python3.7.site-packages.requests.packages.urllib3.packages',
              'env.lib.python3.7.site-packages.requests.packages.urllib3.packages.ssl_match_hostname',
              'env.lib.python3.7.site-packages.socketio', 'env.lib.python3.7.site-packages.werkzeug',
              'env.lib.python3.7.site-packages.werkzeug.debug', 'env.lib.python3.7.site-packages.werkzeug.contrib',
              'env.lib.python3.7.site-packages.werkzeug.wrappers',
              'env.lib.python3.7.site-packages.werkzeug.middleware', 'env.lib.python3.7.site-packages.sseclient',
              'env.lib.python3.7.site-packages.markupsafe', 'env.lib.python3.7.site-packages.python_jwt',
              'env.lib.python3.7.site-packages.setuptools', 'env.lib.python3.7.site-packages.setuptools.extern',
              'env.lib.python3.7.site-packages.setuptools._vendor',
              'env.lib.python3.7.site-packages.setuptools._vendor.packaging',
              'env.lib.python3.7.site-packages.setuptools.command', 'env.lib.python3.7.site-packages.itsdangerous',
              'env.lib.python3.7.site-packages.oauth2client', 'env.lib.python3.7.site-packages.oauth2client.contrib',
              'env.lib.python3.7.site-packages.oauth2client.contrib.django_util',
              'env.lib.python3.7.site-packages.pkg_resources', 'env.lib.python3.7.site-packages.pkg_resources.extern',
              'env.lib.python3.7.site-packages.pkg_resources._vendor',
              'env.lib.python3.7.site-packages.pkg_resources._vendor.packaging',
              'env.lib.python3.7.site-packages.flask_socketio', 'env.lib.python3.7.site-packages.pyasn1_modules',
              'env.lib.python3.7.site-packages.requests_toolbelt',
              'env.lib.python3.7.site-packages.requests_toolbelt.auth',
              'env.lib.python3.7.site-packages.requests_toolbelt.utils',
              'env.lib.python3.7.site-packages.requests_toolbelt.cookies',
              'env.lib.python3.7.site-packages.requests_toolbelt.adapters',
              'env.lib.python3.7.site-packages.requests_toolbelt.threaded',
              'env.lib.python3.7.site-packages.requests_toolbelt.multipart',
              'env.lib.python3.7.site-packages.requests_toolbelt.downloadutils'],
    url='https://blackjack-josh-esteban.herokuapp.com/',
    license='',
    author='admin',
    author_email='',
    description=''
)
